### ISSUE TITLE
Isosurface with with unstructured wedge grid lighting broken

### ISSUE THREAD

**Issue by StasJ** [ospray/ospray#344] opened 2019-08-02 18:04 UTC
Same situation as #343 

Notice the regular gradient instead of proper lighting:

![1](https://user-images.githubusercontent.com/2772687/62389630-8e719c00-b51d-11e9-8784-c32fd41a38b7.png)

![2](https://user-images.githubusercontent.com/2772687/62389632-8fa2c900-b51d-11e9-9992-6b23bfc9bf58.png)

I enabled ambient occlusion to show that there is in fact detail:

![3](https://user-images.githubusercontent.com/2772687/62389647-97fb0400-b51d-11e9-9255-9a7c9492f606.png)

**Comment by johguenther** [comment] 2020-09-23 06:44
Looks to me like a duplicate of #446 (fixed in `devel`).

**Comment by johguenther** [comment] 2020-09-24 08:17
Closing as duplicate of #446.

**Closed by johguenther** 2020-09-24 08:17 UTC
