### ISSUE TITLE
Version 1.4.3 failsto build: redefinition of enumerator 'OSP_VOLUME'

### ISSUE THREAD

**Issue by yurivict** [ospray/ospray#211] opened 2018-01-10 14:55 UTC
I am getting a lot of errors like this:
```
In file included from /usr/ports/science/OSPRay/work/ospray-1.4.3/ospray/include/ospray/ospray.h:44:
/usr/ports/science/OSPRay/work/ospray-1.4.3/ospray/include/ospray/OSPDataType.h:43:3: error: redefinition of enumerator 'OSP_VOLUME'
  OSP_VOLUME,
  ^
/usr/local/include/ospray/OSPDataType.h:43:3: note: previous definition is here
  OSP_VOLUME,
  ^
```

**Comment by johguenther** [comment] 2018-01-10 15:07
There seems to be a conflict in include paths: the headers of your locally installed version of OSPRay are also included.

**Comment by yurivict** [comment] 2018-01-10 15:12
> the headers of your locally installed version of OSPRay are also included.

You should supply local OSPRay headers ahead of /usr/local/include so that the pre-installed version will have no effect.

**Comment by johguenther** [comment] 2018-01-10 16:08
Hmm, I cannot reproduce the issue. Even when having Embree and OSPRay installed locally (at `/usr/local`) that include path already comes after OSPRay headers. The only include path that comes before is the one of TBB, which might cause the problem. Do you have the used TBB installed at `/usr/local`?

**Comment by yurivict** [comment] 2018-01-10 16:12
> Hmm, I cannot reproduce the issue. 

You should try to add some obvious error into the pre-installed headers.
Here I had the older version installed when it was failing. Now I removed it, and it succeeds.

**Comment by johguenther** [comment] 2018-01-11 09:39
This issues seems to be tightly related to your specific build setup, and although mimicking  that as close as possible with the available information I still cannot reproduce the error.

So, if you like us to further investigate please provide more details, i.e. contents of `CMakeCache.txt` and one failing compiler command-line. Otherwise let's close it.

**Comment by yurivict** [comment] 2018-01-11 11:26
This is, I believe, a generic problem. The headers under PREFIX are included before the headers in the project.

The failed line:
```
FAILED: apps/common/sg/CMakeFiles/ospray_sg.dir/common/Data.cpp.o 
/usr/bin/c++  -DOSPRAY_TASKING_TBB -Dospray_sg_EXPORTS -I. -I/usr/local/include -I/usr/ports/science/OSPRay/work/ospray-1.4.3/components -I/usr/ports/science/OSPRay/work/ospray-1.4.3/ospray/include -I/usr/ports/science/OSPRay/work/ospray-1.4.3 -I/usr/ports/science/OSPRay/work/ospray-1.4.3/apps -I/usr/ports/science/OSPRay/work/ospray-1.4.3/apps/common -I/usr/ports/science/OSPRay/work/ospray-1.4.3/apps/common/sg -Iapps/common/sg -Weverything -Wno-format-nonliteral -Wno-shadow -Wno-over-aligned -Wno-disabled-macro-expansion -Wno-mismatched-tags -Wno-deprecated -Wno-cast-align -Wno-float-equal -Wno-switch-enum -Wno-unused-template -Wno-global-constructors -Wno-exit-time-destructors -Wno-weak-vtables -Wno-weak-template-vtables -Wno-shadow-field-in-constructor -Wno-padded -Wno-shift-sign-overflow -Wno-missing-prototypes -Wno-missing-noreturn -Wno-old-style-cast -Wno-used-but-marked-unused -Wno-double-promotion -Wno-reserved-id-macro -Wno-conversion -Wno-keyword-macro -Wno-newline-eof -Wno-zero-as-null-pointer-constant -Wno-documentation-unknown-command -Wno-documentation -Wno-c++98-compat-pedantic -std=c++11 -fPIC -fno-strict-aliasing -Wno-narrowing -O2 -pipe -fno-omit-frame-pointer -fstack-protector -fno-strict-aliasing -fno-omit-frame-pointer -DNDEBUG    -O3 -Wstrict-aliasing=1 -fPIC -MD -MT apps/common/sg/CMakeFiles/ospray_sg.dir/common/Data.cpp.o -MF apps/common/sg/CMakeFiles/ospray_sg.dir/common/Data.cpp.o.d -o apps/common/sg/CMakeFiles/ospray_sg.dir/common/Data.cpp.o -c /usr/ports/science/OSPRay/work/ospray-1.4.3/apps/common/sg/common/Data.cpp
```

[CMakeCache.txt](https://github.com/ospray/ospray/files/1622329/CMakeCache.txt)

**Comment by johguenther** [comment] 2018-01-11 13:03
Thanks for the info. I still don't fully understand the root cause, nor can replicate it; here is what I found so far:
- the first include dir is `PROJECT_BINARY_DIR`, "." in your case, which is strange, because `PROJECT_BINARY_DIR` should contain the *full path* according to CMake documentation. Changing it manually to "." does still not trigger the error on my side.
- the 2nd include dir is `TBB_INCLUDE_DIR` (and not `PREFIX`, but the same value in your case). However, when system include paths such as `/usr/local/include` are given with  "-I", gcc/clang will ignore that and still only use that path when all other include paths did not work.

I agree that including `TBB_INCLUDE_DIR` before project paths is not optimal, but will only cause problems in very rare cases (when OSPRay and TBB are installed at the same, non-system location). We plan to overhaul our CMake files to not use `include_directories` anymore  (at least for TBB), which should also fix that rare case.

**Comment by johguenther** [comment] 2018-12-06 14:31
Can you please try the v1.7.3?
Closing for now, if the issue persists: please re-open.

**Closed by johguenther** 2018-12-06 14:31 UTC
