### ISSUE TITLE
Loading the  a Point cloud from buffer in ospray

### ISSUE THREAD

**Issue by swatinair123** [ospray/ospray#215] opened 2018-01-15 06:51 UTC
Hi , Can you please tell us how to load the color(rgb)and the xyz points and if the data can be directly loaded from the buffer into ospray. How / which format can we view/load point cloud in ospray .Please kindly advise.
We have given .ply file of the cloud points but it says no triangular mesh.
Thanks in advance

**Comment by carsonbrownlee** [comment] 2018-01-15 07:19
hello, 
the OSPRay library does indeed support colored points, and you can use existing data using the OSP_DATA_SHARED_BUFFER flag to ospNewData.  To see how to set the color, see the "Spheres" section in the API docs for OSPRay.  ParaView also demonstrates this behavior when rendering with OSPRay on colored points.

If you mean the ospExampleViewer (which is just there as example usage of OSPRay), I believe the only point data loader that loads in points with color right now is the one in apps/common/sg/importer/importPoints.cpp .  That one appears to only support a colormap, not direct colors.  importPLY only supports triangle meshes unfortunately.

**Comment by carsonbrownlee** [comment] 2018-01-16 17:30
This appears to be a duplicate of #213.  Closing this one, please post further questions to 213.

**Closed by carsonbrownlee** 2018-01-16 17:30 UTC
