### ISSUE TITLE
increased loading time and crash when using xfrog model with MPI

### ISSUE THREAD

**Issue by dkoerner** [ospray/ospray#80] opened 2016-08-31 10:49 UTC
Hi,

I am running a small standalone ospray application using MPI on a Cray system. The application loads the xfrog-forest model and renders a frame (using ospray_commandline, ospray_cpp etc.).

Now the problem is that the loading time of the xfrog model increases rapidly with the number of mpi workers. On the single node the time spend during loading (done with parseWithDefaultParsers):
1 node 4 ppm (3 mpi workers) -> 20s
1 node 6ppm (5 mpi workers) -> 29s
1 node 12ppm (11 mpi workers) -> 33s
1 node 24 ppn (23 mpi workers) -> 54s

When different nodes are involved, the application segfaults.
2 node 4 ppn (7 mpi workers) ->
_pmiu_daemon(SIGCHLD): [NID 04572] [c11-1c2s7n0] [Wed Aug 31 12:30:24 2016] PE RANK 1 exit signal Segmentation fault
[NID 04572] 2016-08-31 12:30:24 Apid 4989096: initiated application termination
Application 4989096 exit codes: 139
Application 4989096 exit signals: Killed

The increase in loading time appears to come from this loop in TriangleMeshSceneParser::finalize:
https://github.com/ospray/OSPRay/blob/master/apps/common/commandline/SceneParser/trianglemesh/TriangleMeshSceneParser.cpp#L362-L369

As I run this on a single node with 4 workers, it iterates the loop rather quickly. Once the number of workers increases, the loop takes more and more time to iterate. The same is true when multiple nodes are involved. The first iterations go through swiftly and each successive iteration takes increasingly longer. Around the i=318000/377266 mark it crashes when I use multiple nodes.

I thought I run this issue by you guys first before I dig deeper on my own. Maybe there is some communication involved for each added instance which takes a hit with additional workers. If thats the case, maybe some sort of batch instantiation could help. Do you guys have an idea where this could come from and why the application crashes on multiple nodes?

Thanks in advance.

Best,
David

**Comment by carsonbrownlee** [comment] 2016-09-01 04:31
hi David,
thanks for the feedback!  You are right, the initial way we had api calls broadcast over mpi was very inefficient, and it gets worse the more mpi ranks you have.  We currently have an implementation in a development branch that does indeed batch commands together among other changes that make the mpi comm layer more efficient.  One of our developers is currently looking into merging some of those changes with our devel branch (and possible next release) which should help significantly.  I will try to remember to update this issue when that gets put in, hopefully in the next two weeks or so.

I'm not sure why the scene is segfaulting for you on multiple nodes.  We recently ran that model across 22 nodes, so I'll need some help narrowing the seg fault down.  Was this with the "--osp:mpi" flag?  Can you run the same test using our glutViewer app and see if you can replicate the issue?  Can you also test with 1 ppn and see if that fixes the seg fault?  

Thanks!
Carson

**Comment by carsonbrownlee** [comment] 2016-09-01 04:37
on another note, are you running multiple mpi processes per node for the sake of your application code or for testing distributed?  It's always better to run a single process per node with OSPRay when possible.

**Comment by dkoerner** [comment] 2016-09-05 08:50
I am running multiple mpi workers per node just for testing distributed. I'll try a single process per node. Are osprays mpi workers single threaded?

**Comment by johguenther** [comment] 2016-09-05 10:33
No, `ospray_mpi_worker` spawns multiple threads.

**Comment by dkoerner** [comment] 2016-09-19 14:06
Hi Johannes, thanks for the answer. How is each worker determining the number of threads it will use? I just want to make sure that the number of PEs per node matches what the workers will actually use...

**Comment by johguenther** [comment] 2016-09-20 07:21
Per default it is up to the used tasking system to decide the optimal number of threads. This usually works fine, e.g. all PEs are used and also CPU groups / partitions are adhered. If this for some reason does not work you might use the parameter `--osp:numthreads <n>` to override the automatic behaviour.

**Comment by dkoerner** [comment] 2016-09-20 16:41
ah ok thanks. 
Just out of curiosity: how does the worker know how many PE's he can use for multithreading? As far as my limited understanding goes, there might be other PE's in use on that node by other users/applications, right?

**Comment by carsonbrownlee** [comment] 2016-09-20 19:50
TBB will auto detect the number of virtual cores to run on a system, but it's up to the user to avoid thread over-utilization by setting the number of threads as Johannes described when running multiple MPI processes on a single node or other resource heavy applications.

**Comment by dkoerner** [comment] 2016-09-21 14:28
When I kick of ospray on the cray, I have to specify the amount of PEs per node which I want to allocate using the aprun command. Doing that results in ospray detecting every single PE as seperate MPI instance, which---as it sounds---will internally be multithreaded.

How can I allocate resources (using aprun) and at the same time make sure that a single mpi instance is running per node with all other PEs on that node being used/available for multithreading?

Thanks for your patience and for bearing with all my questions! Much appreciated!

**Comment by Twinklebear** [comment] 2016-09-22 01:02
I'm not familiar with aprun but on the TACC machines (and with mpirun) there's usually some argument (or environment variable) to set the number of cores per node or cores per rank that are assigned. So there should be some way you can specify to use N nodes with 1 ospray process per node and each process assigned all M cores on its node.

**Comment by ingowald** [comment] 2016-09-22 18:37
David,

I am not familiar w/ aprun, but here is something that might be useful:

http://www.nersc.gov/users/computational-systems/retired-systems/hopper/running-jobs/using-openmp-with-mpi/

Of course we use TBB rather than OpenMP, but the problem is exactly the 
same: you want fewer MPI tasks per node than there are PEs, and want 
those MPI tasks to fill the PEs using threads. Unlike tihs document we 
suggest is a single MPI task per node (this document suggest four); but 
this should allow you to adapt the parameters accordingly.


Hope this helps - if it does, feel free to put a little page onto the 
github wiki ;-)

Cheers,

Ingo

**Comment by carsonbrownlee** [comment] 2016-10-24 20:42
@Twinklebear what's the status of merging in the work unit batching with devel?

**Comment by Twinklebear** [comment] 2016-10-24 21:13
@carsonbrownlee I've got the crash when exiting fixed but only with a hack, I need to add in the management class you mentioned in the comment in `mpi/MPICommon.cpp`. The other stuff left to do is have work units indicate if the master should run them or not in master/worker mode (currently the master runs everything). You can currently run the ospGlutViewer with the batching but volumes crash currently (my guess is b/c of this issue)

**Comment by carsonbrownlee** [comment] 2018-01-01 23:02
while this can still be optimized, message batching (now called buffered write/read streams) was merged into OSPRay proper a while ago which should mitigate load times over MPI.

**Closed by carsonbrownlee** 2018-01-01 23:02 UTC
