### ISSUE TITLE
seg fault with ospModelViewer with the xfrog-forest model

### ISSUE THREAD

**Issue by kimwooyoung** [ospray/OSPRay#12] opened 2015-03-04 19:56 UTC
Hi,
I downloaded ospray 0.7.1 and installed on a Linux box and ran ospModelViewer with xfrog-forest as shown in http://ospray.github.io/demos.html.
And I got the following segf-fault. I am using ispc 1.8.1

MSG Viewer created. Press 'Q' to quit.
glut3d: setting world bounds [(-6.3012, -5.48216, -5.84341); (303.669, 38.3725, 303.561)], motion speed 0.457437

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5869700 (LWP 37829)]
0x00007ffff76c38e9 in TriangleMesh_postIntersect___un_3C_s[unGeometry]_3E_un_3C_s[unModel]_3E_REFs[vyDifferentialGeometry]REFs[_c_vyRay]unI ()
   from /localdisk/wkim3/repo/projects/ospray-0.7.1/build/libospray.so.0
(gdb) bt
#0  0x00007ffff76c38e9 in TriangleMesh_postIntersect___un_3C_s[unGeometry]_3E_un_3C_s[unModel]_3E_REFs[vyDifferentialGeometry]REFs[_c_vyRay]unI ()
   from /localdisk/wkim3/repo/projects/ospray-0.7.1/build/libospray.so.0
Backtrace stopped: Cannot access memory at address 0x7f8000007f7fffd8

Interestingly, the debug build ran fine with the model without any issue.

thanks

-wooyoung

**Comment by ingowald** [comment] 2015-03-04 21:32
Interesting indeed, in particular that the debug build ran through.
Did you use the proper ISA when compiling (i.e., not compiling for AVX2 
and running on a SSE-only machine?)

And can you tell us a bit more about
a) which exact version you are using (0.7.1 release, master brnach?)
and
b) which OS (which linux, macos, etc), CPU type (under linux: cat 
/proc/cpuinfo) and compiler (gcc/icc version)
you are using?

We'll be having a look right away, but the more information we have the 
easier it is to reproduce this one on our side...

Cheers,

Ingo

**Comment by kimwooyoung** [comment] 2015-03-04 22:38
I built it on an SNB Linux box. AVX2 was OFF.
( from CMakeCache.txt: OSPRAY_XEON_TARGET:STRING=AVX )

a) I think I downloaded a 'zip' version from the git hub download page. 
b) Linux, LDE EL6S, SNB 16C/32T. CPU Family 6 Model 45.
c) Compiler GCC 4.9.2, ICC 15.0.2 ISPC 1.8.1

Please feel free to let me know if you need more info.

-thanks

**Comment by ingowald** [comment] 2015-03-04 23:36
Thanks for that info, Kim,

We'll be looking at it next time we're all back in the office together 
(we have more machines and more different compiler/OS variants there).
I just tried locally and it worked without a hitch, but we'll be trying 
to reproduce your exact setup...

Just double-checking: You're using ISPC 1.8.1. *binary*, or did you 
build your own from scratch?

Cheers,

Ingo

**Comment by kimwooyoung** [comment] 2015-03-05 16:27
I built ISPC 1.8.1 locally from the scratch.

**Comment by ingowald** [comment] 2015-03-05 16:49
Can you please try using the binary distribution off the ispc download page?
When you build from scratch there could be any number of bugs in the live version you used to build it with that we cannot reproduce.

Pls try the binary ispc distribution, and make sure that the ospray build then uses the 'correct' ispc version, and has no stale files from the 'old' ispc lying around any more...

**Comment by kimwooyoung** [comment] 2015-03-06 15:37
I tried the ispc 1.8.1 binary distribution and the same thing happened.

release >             which ispc
ispc is /tmp/ispc-v1.8.1-linux/ispc

-wooyoung

**Comment by ingowald** [comment] 2015-04-17 20:48
could not reproduce (tried multiple configurations). Closing this.

**Closed by ingowald** 2015-04-17 20:48 UTC
