### ISSUE TITLE
ISPC v1.11.0 compile issues

### ISSUE THREAD

**Issue by sriravic** [ospray/ospray#322] opened 2019-05-10 22:57 UTC
When trying to compile the latest pulled code on a Ubuntu 18.04 system with clang-8 and the latest ispc1.11, build fails with the following error.

```
/usr/bin/ld: local__common/OSPCommon.dev_sse4.o: relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
```

I checked the ispc flags and they are indeed built with `--pic` flags. I'm not sure what else is going wrong here.

**Comment by jeffamstutz** [comment] 2019-05-10 23:07
Yes, this is a known new issue with the latest ISPC (v1.11.0) and OSPRay. I've done some initial explorations and haven't been able to get it working locally.

The current workaround is to use ISPC v1.10.0 until we can figure out these PIC related problems.

**Comment by sriravic** [comment] 2019-05-10 23:41
Thank you. That fixed the problem. Should I close this issue or keep it open for tracking purposes?

**Comment by jeffamstutz** [comment] 2019-05-11 04:22
Let’s leave this open until the ISPC issues are ironed out, so this gets tracked in a public place.

**Comment by dbabokin** [comment] 2019-05-13 04:15
CCing @aneshlya

**Comment by johguenther** [comment] 2019-05-13 09:28
Just out of curiosity: did you manually enforce usage of ispc v1.11? Because we have
```cmake
set(ISPC_VERSION_WORKING "1.10.0" "1.9.2" "1.9.1")
```
in `ospcommon/cmake/ispc.cmake`, thus that version should not have been picked up automatically by CMake configure.

**Comment by sriravic** [comment] 2019-05-13 11:55
I didn't enforce it directly but rather my setup just had version 1.11 in the path to search for the ispc executable. I'm not sure why CMake didn't report this.

**Comment by dbabokin** [comment] 2019-05-14 00:58
This ISPC problem. We have a fix for it.

**Comment by dbabokin** [comment] 2019-05-15 00:27
The issue is fixed in ISPC master. It will be available in the next ISPC release.

**Comment by jeffamstutz** [comment] 2019-05-15 00:31
Fantastic, thanks @dbabokin!

**Comment by jeffamstutz** [comment] 2019-10-04 16:33
We now detect if an incompatible ISPC is being used during CMake build configuration in `v2.0.0-alpha`.

**Closed by jeffamstutz** 2019-10-04 16:33 UTC

**Comment by dbabokin** [comment] 2019-10-04 20:44
I see that you have list of compatible versions here: https://github.com/ospray/ospray/blob/master/components/ospcommon/cmake/ispc.cmake#L18

What about adding 1.12.0 to it?
