### ISSUE TITLE
Build fails in the presence of the pre-installed package

### ISSUE THREAD

**Issue by yurivict** [ospray/ospray#98] opened 2016-11-17 17:56 UTC
It apparently includes its headers twice:

```
In file included from /usr/ports/graphics/ospray/work/OSPRay-1.1.1/ospray/api/API.cpp:18:
In file included from /usr/ports/graphics/ospray/work/OSPRay-1.1.1/ospray/include/ospray/ospray.h:44:
/usr/ports/graphics/ospray/work/OSPRay-1.1.1/ospray/include/ospray/OSPDataType.h:24:3: error: redefinition of enumerator 'OSP_VOID_PTR'
  OSP_VOID_PTR,
  ^
/usr/local/include/ospray/OSPDataType.h:24:3: note: previous definition is here
  OSP_VOID_PTR,
  ^
In file included from /usr/ports/graphics/ospray/work/OSPRay-1.1.1/ospray/api/API.cpp:18:
In file included from /usr/ports/graphics/ospray/work/OSPRay-1.1.1/ospray/include/ospray/ospray.h:44:
/usr/ports/graphics/ospray/work/OSPRay-1.1.1/ospray/include/ospray/OSPDataType.h:27:3: error: redefinition of enumerator 'OSP_OBJECT'
  OSP_OBJECT,
  ^
/usr/local/include/ospray/OSPDataType.h:27:3: note: previous definition is here
  OSP_OBJECT,
  ^
```

**Comment by johguenther** [comment] 2018-02-28 10:15
Duplicate of #211.

**Closed by johguenther** 2018-02-28 10:15 UTC
