### ISSUE TITLE
Affine transformation for volume

### ISSUE THREAD

**Issue by wilsonCernWq** [ospray/ospray#159] opened 2017-07-22 00:59 UTC
Hi, 

I am wondering how could I do affine transformation for rendering volume. 

Volume renderers in VisIt use openGL style matrices to manipulate (e.g. non-isotropic scaling) and project volume before raycasting, so I need to implement the same functionality using OSPRay. 

I am thinking of two ways to implement it, but not very sure which one is better.

* Implement an `instance` class similar to that for `Geometry`
* Implement a (or two) new `camera` for that.

Can I get some suggestions ? Or please let me know if there are better ways of doing it.

Thanks

Qi

**Comment by johguenther** [comment] 2017-07-24 07:56
The first option is the preferred way; it's actually a duplicate of #48 – we should really get this implemented...

**Comment by wilsonCernWq** [comment] 2017-07-24 16:27
I read the code in `ospray/geometry/Instance.cpp` and I noticed it uses some embree functions, for example, [`rtcNewInstance`](https://github.com/ospray/ospray/blob/devel/ospray/geometry/Instance.cpp#L51) and [`rtcSetTransform`](https://github.com/ospray/ospray/blob/devel/ospray/geometry/Instance.cpp#L82).

However volumes are not rendered by embree, so how should we do an instantiation? All I can think of is creating a dummy volume type and apply tricks during sampling. Will that work?

**Comment by jeffamstutz** [comment] 2017-07-24 16:51
I think a good approach would be to have Embree do all intersections, where an Embree UDG (implementing a "box" primitive) would be used to represent the bounds of the volume. Volumes would then be a special type that does its volume sample accumulation in ```postIntersect()``` (or something like that if ```postIntersect()``` doesn't make sense). Then from Embree's perspective its just another "geometry" enabling all of Embree's instancing features, though we wouldn't treat it as a geometry in our renderers.

Unfortunately, right now the renderers have special knowledge that volumes exist in the ```OSPModel``` and handle them separately from Embree. In other words, the renderer does the work of doing ray-box intersections to find in/out points to accumulate volume samples between. The complicated implementation of the ```scivis``` renderer makes this a little tricky, but ultimately doable.

**Comment by wilsonCernWq** [comment] 2017-07-24 17:31
@jeffamstutz What you said makes a lot of sense, but it seems we need to rewrite the whole renderer and volume types. That will be a huge work to do. However from my perspective, I want a quick solution to fix the rendering bugs caused by that in my project.

What I am thinking is to create a class called for example `volumeInstance`, which contains an affine `transformation` and a new `boundingbox`. It also has to wrap some function pointers inside `Volume` class.

for example, for `computeSample` function, the function wrapper will first transfer `worldCoordinates` into the original coordinate using the inverse of the affine `transformation`, and call the sampling function from its associated volume type. For functions like `intersect`, maybe I can transform the ray back also. I feel this is a doable solution in the short term.

**Comment by carsonbrownlee** [comment] 2017-07-24 18:31
making the volume a geometry is actually an existing issue on gitlab we haven't gotten around to implementing yet.  Without making that change, a modification to the renderer to intersect a dummy bound as jeff mentioned, transforming and untransforming the ray on ray exit, shouldn't be too bad.  I would advocate for explicitly putting this into VolumeIntegrate for now instead of transforming on every sample operation.

**Comment by wilsonCernWq** [comment] 2017-07-24 19:12
If I need to implement the instance class, should I associated one instance to one model or one single volume? Why in geometry, we choose to associated it to a model in the first place ?

**Comment by wilsonCernWq** [comment] 2017-08-02 23:23
I am just wondering is there any updates about this problem. I hope someone can get this fixed recently, because we want this functionality urgently. Thanks !

At the meanwhile, I made a [volume](https://github.com/wilsonCernWq/ospray/blob/visit-affine-volume/modules/visit/ospray/volume/InstanceVolume.ispc) type in my module. However my volume doesn't work as expected.

I changed function pointers in this volume in [InstanceVolume_setValues](https://github.com/wilsonCernWq/ospray/blob/visit-affine-volume/modules/visit/ospray/volume/InstanceVolume.ispc#L101) as the following
```
self->super.computeSample = InstanceVolume_computeSample;  
self->super.computeGradient = InstanceVolume_computeGradient;  
self->super.intersect = InstanceVolume_intersect;
self->super.intersectAdaptive = InstanceVolume_intersectAdaptive;
self->super.intersectIsosurface = InstanceVolume_intersectIsosurface;
```
And then created volume like the following
```
        OSPModel localWorld = ospNewModel();
        ospAddVolume(localWorld, volume);
        ospCommit(localWorld);
        ospRelease(volume);

        OSPVolume instanceVolume = ospNewVolume("instance_volume");
        ospSetObject(instanceVolume, "model", localWorld);
        ospSetVec3f(instanceVolume, "xfm.l.vx", osp::vec3f{5.0f, 0.0f, 0.0f});
        ospSetVec3f(instanceVolume, "xfm.l.vy", osp::vec3f{0.0f, 1.0f, 0.0f});
        ospSetVec3f(instanceVolume, "xfm.l.vz", osp::vec3f{0.0f, 0.0f, 1.0f});
        ospSetVec3f(instanceVolume, "xfm.p",    osp::vec3f{0.0f, 0.0f, 0.0f});
        ospCommit(instanceVolume);
        ospAddVolume(world, instanceVolume);
```
But when I ran my testing program, only [InstanceVolume_setValues](https://github.com/wilsonCernWq/ospray/blob/visit-affine-volume/modules/visit/ospray/volume/InstanceVolume.ispc#L101) was called. Function pointers like `intersectAdaptive` was pointed to functions coming from the instanced volume class.

Can anyone give me some help ?

**Comment by jeffamstutz** [comment] 2017-08-03 16:24
Hi,

Stupid questions: 

- you're using the ```scivis``` renderer?
- have you verified that the bounding box (pre + post transform) is what you expect?
- did you commit the original volume?
- when you use the original volume instead of the instanced version, does it render correctly for you (minus the transform, of course)?
- what type of volume are you instantiating?

Other observations:

- It doesn't look like there's any need to put the original volume in an ```OSPModel```. We do that with geometries for other reasons (it's a grouping construct).
- I'm not sure if this approach will give you the final result you are looking for anyway: all bounding boxes are axis aligned (you only specify two corners), so you can only use the transform to move a volume around the given axes. If that's all you are trying to do, then this might be OK, but the general transform solution will require the renderer to transform rays. Unfortunately, our ```volume->intersect``` function is not well named as that actually just steps the ray forward, it doesn't do arbitrary bounding box intersection. That is done manually by the renderer (see ```SciVisRenderer_intersectVolumes()``` in [volumeIntegration.ispc](https://github.com/ospray/ospray/blob/devel/ospray/render/scivis/volumeIntegration.ispc)).

Cheers,
Jeff

**Comment by wilsonCernWq** [comment] 2017-08-07 22:43
Hi Jeff

Answers to your questions:
* `you're using the scivis renderer?` yes I am using _scivis_ renderer

* `have you verified that the bounding box (pre + post transform) is what you expect?
did you commit the original volume?` I did. I printed the transformed bounding box in `InstanceVolume_setValues` function. They are correct. 

* `when you use the original volume instead of the instanced version, does it render correctly for you (minus the transform, of course)?` it does render correctly.

* `what type of volume are you instantiating?` shared structured volume

* `It doesn't look like there's any need to put the original volume in an OSPModel. We do that with geometries for other reasons (it's a grouping construct).` I fixed it.

* `(last question)` I think you are right. [`intersectBox`](https://github.com/wilsonCernWq/ospray/blob/visit-affine-volume/ospray/common/Ray.ih#L126) assumes the boundingbox is AABB. So how about adding the affine transformations into `Volume` class, and transform it somewhere in scivis renderer?

**Comment by wilsonCernWq** [comment] 2017-08-08 00:19
It seems this [commit](https://github.com/wilsonCernWq/ospray/commit/f5c85966140a1ce4735944bc7c352d0a12322761) works.

My problem seems to be solved!

**Comment by jeffamstutz** [comment] 2017-08-08 00:34
Cool, would you be willing to contribute this as a Pull Request to ```devel```? If so, it would ideally be a single commit with your changes.

**Comment by wilsonCernWq** [comment] 2017-08-08 02:41
@jeffamstutz Sure, I just cleaned my changes and created a pull request ! Thanks.

**Comment by jeffamstutz** [comment] 2017-08-08 16:05
NOTE: this was merged into ```devel``` in #165.

**Comment by carsonbrownlee** [comment] 2017-08-09 22:03
I have temporarily reverted this, it is causing a stall when running a test with csafe after a few hundred frames.  With and without plane.  removing ray transforms makes this go away.  Assuming it is likely hitting an infinite look due to unhandled edge case, will look into it further.

**Comment by carsonbrownlee** [comment] 2017-08-09 22:05
Also, I have added code to Instance.cpp that automatically sets the transform values for the volumes in the model.  This will break nested instancing and should be replaced when we merge the volume into a geometry type.

**Comment by paulmelis** [comment] 2018-12-03 19:55
Is there currently any way to apply an affine transform to a volume? If I read the above correctly #165 was reverted. Testing with that method indeed seems not to apply a transform with 1.7.2.

And there's also no way to instantiate a volume using `ospNewInstance` and set the transform there.

**Comment by carsonbrownlee** [comment] 2018-12-04 15:22
yes it was taken out and never properly fixed so was not put back in.  this is absolutely something we want to support, but it may wait for ospray 2.0.

**Comment by surfsara-visualization** [comment] 2018-12-04 16:05
Ok, good to know that it is coming at some point. I guess I'll locally re-enable the commit at some pont just to get some transformation working. But I am wondering how sciviz packages that incorporate ospray, like VTK, ParaView and VisIt are handling this, are they not supporting any transform on volumes?

**Comment by johguenther** [comment] 2018-12-04 16:08
Scaling and translation are supported via the `gridSpacing` and `gridOrigin` parameters of volumes.

**Comment by surfsara-visualization** [comment] 2018-12-04 16:11
Ah, that's right, forgot about that one for structured grids. So rotation is the one biggy missing there. And with unstructured volumes transforming the vertices is a work-around, so for now one can turn a structured grid into a hexahedral grid and transform its vertices. Not pretty, but should work.

**Comment by jeffamstutz** [comment] 2019-02-06 02:10
We are planning to make everything instanced for `v2.0`, including all volume types. I'll close this issue as the current `v1.8.x` API is not going to be updated as-is, but the feature will be a part of `v2.0`.

**Closed by jeffamstutz** 2019-02-06 02:10 UTC
